#############################################################################
#  IRI Facility API reference implementation Copyright (c) 2025,
#  The Regents of the University of California, through Lawrence
#  Berkeley National Laboratory (subject to receipt of any required
#  approvals from the U.S. Dept. of Energy).  All rights reserved.
#
#  If you have questions about your rights to use or distribute this
#  software, please contact Berkeley Lab's Innovation & Partnerships
#  Office at IPO@lbl.gov.
#
#  NOTICE.  This Software was developed under funding from the
#  U.S. Department of Energy and the U.S. Government consequently retains
#  certain rights. As such, the U.S. Government has been granted for
#  itself and others acting on its behalf a paid-up, nonexclusive,
#  irrevocable, worldwide license in the Software to reproduce,
#  distribute copies to the public, prepare derivative works, and perform
#  publicly and display publicly, and to permit other to do so.
#############################################################################

# Standard spring runtime configuration.
server:
  port: 8081  # Change to the desired port number
  servlet:
    context-path: /

# Standard logging runtime configuration.
logging:
  level:
    root: INFO
    net.es.iri.api.facility: DEBUG  # Change package-level logging

# This is the path to expose the swagger generated documentation.
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /v3/swagger-ui

# Application specific configuration.
iri:
  server:
    root: "http://localhost:8081"
    #proxy: "https://iri.es.net"

# IRI Facility API test data.
status:
  facilities:
    - id: "09a22593-2be8-46f6-ae54-2904b04e13a4"
      name: "National Energy Research Scientific Computing Center"
      shortName: "NERSC"
      description: "NERSC is the mission scientific computing facility for the U.S. Department of Energy Office of Science, the nation’s single largest supporter of basic research in the physical sciences."
      lastModified: "2025-03-03T20:57:49.690-00:00"
      organizationName: "Lawrence Berkeley National Laboratory"
      links:
        - rel: "self"
          href: "/api/v1/status/facility"
        - rel: "hasSupportURL"
          href: "https://help.nersc.gov/"
        - rel: "hostedAt"
          href: "/api/v1/status/sites/ce2bbc49-ba63-4711-8f36-43b74ec2fe45"
        - rel: "hasResource"
          href: "/api/v1/status/resources/289d38f2-e93c-4840-b037-8b78d8ec36cc"
        - rel: "hasResource"
          href: "/api/v1/status/resources/29ea05ad-86de-4df8-b208-f0691aafbaa2"
        - rel: "hasResource"
          href: "/api/v1/status/resources/29989783-bc70-4cc8-880f-f2176d6cec20"
        - rel: "hasResource"
          href: "/api/v1/status/resources/303a692d-c52b-47f0-8699-045f962650e2"
        - rel: "hasResource"
          href: "/api/v1/status/resources/b06f8043-f96b-4279-8f0a-0e128a73cc32"
        - rel: "hasResource"
          href: "/api/v1/status/resources/ff415c87-6596-41c7-93fd-b772994a92d4"
        - rel: "hasResource"
          href: "/api/v1/status/resources//0918ad2e-b318-4fd1-ac8f-56a55abf8e8d"
        - rel: "hasResource"
          href: "/api/v1/status/resources/f8a06086-b79b-4f45-beec-abb8bee38fa1"
        - rel: "hasResource"
          href: "/api/v1/status/resources/057c3750-4ba1-4b51-accf-b160be683d80"
        - rel: "hasResource"
          href: "/api/v1/status/resources/097c3750-4ba1-4b51-accf-b160be683d55"
        - rel: "hasResource"
          href: "/api/v1/status/resources/13f886ac-6cc2-47c0-a5d4-d82daf3cf5c6"
        - rel: "hasResource"
          href: "/api/v1/status/resources/8b61b346-b53c-4a8e-83b4-776eaa14cc67"
        - rel: "hasResource"
          href: "/api/v1/status/resources/a0d96526-6fd3-413e-8f9e-ff12d602539e"
        - rel: "hasResource"
          href: "/api/v1/status/resources/43b698c6-ed4a-4c1c-90b6-f8829daa9e96"
        - rel: "hasResource"
          href: "/api/v1/status/resources/be85a1f4-292e-44d7-804d-68a7ca3e0a1e"
        - rel: "hasResource"
          href: "/api/v1/status/resources/b1ce8cd1-e8b8-4f77-b2ab-152084c70281"
        - rel: "hasResource"
          href: "/api/v1/status/resources/72c11ef6-ff6b-409e-adfd-2f3763daac4f"
        - rel: "hasResource"
          href: "/api/v1/status/resources/3594b493-f811-43b9-9c14-a3dd23542ffc"
        - rel: "hasResource"
          href: "/api/v1/status/resources/d3c52e3c-dd2a-47a4-91e7-f06e00cf486d"
        - rel: "hasResource"
          href: "/api/v1/status/resources/b951a092-7f0a-4263-bc9a-700c7ceed415"
  sites:
    - id: "ce2bbc49-ba63-4711-8f36-43b74ec2fe45"
      name: "Lawrence Berkeley National Laboratory Building 59"
      shortName: "LBNL59"
      description: "Building 59 is a medium-sized office building with two office floors, one mechanical equipment floor, and one floor for NERSC data and computing center."
      lastModified: "2025-03-04T09:00:00.690-00:00"
      links:
        - rel: "self"
          href: "/api/v1/status/sites/ce2bbc49-ba63-4711-8f36-43b74ec2fe45"
        - rel: "locatedAt"
          href: "/api/v1/status/locations/b1c7773f-4624-4787-b1e9-46e1c78c3320"
        - rel: "hasResource"
          href: "/api/v1/status/resources/289d38f2-e93c-4840-b037-8b78d8ec36cc"
        - rel: "hasResource"
          href: "/api/v1/status/resources/29ea05ad-86de-4df8-b208-f0691aafbaa2"
        - rel: "hasResource"
          href: "/api/v1/status/resources/29989783-bc70-4cc8-880f-f2176d6cec20"
        - rel: "hasResource"
          href: "/api/v1/status/resources/303a692d-c52b-47f0-8699-045f962650e2"
        - rel: "hasResource"
          href: "/api/v1/status/resources/b06f8043-f96b-4279-8f0a-0e128a73cc32"
        - rel: "hasResource"
          href: "/api/v1/status/resources/ff415c87-6596-41c7-93fd-b772994a92d4"
        - rel: "hasResource"
          href: "/api/v1/status/resources//0918ad2e-b318-4fd1-ac8f-56a55abf8e8d"
        - rel: "hasResource"
          href: "/api/v1/status/resources/f8a06086-b79b-4f45-beec-abb8bee38fa1"
        - rel: "hasResource"
          href: "/api/v1/status/resources/057c3750-4ba1-4b51-accf-b160be683d80"
        - rel: "hasResource"
          href: "/api/v1/status/resources/097c3750-4ba1-4b51-accf-b160be683d55"
        - rel: "hasResource"
          href: "/api/v1/status/resources/13f886ac-6cc2-47c0-a5d4-d82daf3cf5c6"
        - rel: "hasResource"
          href: "/api/v1/status/resources/8b61b346-b53c-4a8e-83b4-776eaa14cc67"
        - rel: "hasResource"
          href: "/api/v1/status/resources/a0d96526-6fd3-413e-8f9e-ff12d602539e"
        - rel: "hasResource"
          href: "/api/v1/status/resources/43b698c6-ed4a-4c1c-90b6-f8829daa9e96"
        - rel: "hasResource"
          href: "/api/v1/status/resources/be85a1f4-292e-44d7-804d-68a7ca3e0a1e"
        - rel: "hasResource"
          href: "/api/v1/status/resources/b1ce8cd1-e8b8-4f77-b2ab-152084c70281"
        - rel: "hasResource"
          href: "/api/v1/status/resources/72c11ef6-ff6b-409e-adfd-2f3763daac4f"
        - rel: "hasResource"
          href: "/api/v1/status/resources/3594b493-f811-43b9-9c14-a3dd23542ffc"
        - rel: "hasResource"
          href: "/api/v1/status/resources/d3c52e3c-dd2a-47a4-91e7-f06e00cf486d"
        - rel: "hasResource"
          href: "/api/v1/status/resources/b951a092-7f0a-4263-bc9a-700c7ceed415"
      operatingOrganization: "Lawrence Berkeley National Laboratory"
  resources:
    - id: "289d38f2-e93c-4840-b037-8b78d8ec36cc"
      name: "help.nersc.gov"
      shortName: "service_now"
      description: "The NERSC help portal."
      lastModified: "2025-03-03T07:50:20.672-00:00"
      links:
        - rel: "self"
          href: "/api/v1/status/resources/289d38f2-e93c-4840-b037-8b78d8ec36cc"
      type: "website"
      group: "websites"
      current-status: "up"
    - id: "29ea05ad-86de-4df8-b208-f0691aafbaa2"
      name: "Scratch"
      shortName: "scratch"
      description: "The Perlmutter Scratch File System is an all-flash file system."
      lastModified: "2025-03-03T07:51:20.672-00:00"
      links:
        - rel: "self"
          href: "/api/v1/status/resources/29ea05ad-86de-4df8-b208-f0691aafbaa2"
      type: "storage"
      group: "perlmutter"
      current-status: "up"
    - id: "29989783-bc70-4cc8-880f-f2176d6cec20"
      name: "iris.nersc.gov"
      shortName: "iris"
      description: "Account management system."
      lastModified: "2025-03-03T07:51:20.672-00:00"
      links:
        - rel: "self"
          href: "/api/v1/status/resources/29989783-bc70-4cc8-880f-f2176d6cec20"
      type: "website"
      group: "websites"
      current-status: "up"
    - id: "303a692d-c52b-47f0-8699-045f962650e2"
      name: "HPSS Archive (User)"
      shortName: "archive"
      description: "NERSC account management system."
      lastModified: "2025-03-03T07:51:20.672-00:00"
      links:
        - rel: "self"
          href: "/api/v1/status/resources/303a692d-c52b-47f0-8699-045f962650e2"
      type: "storage"
      group: "storage"
      current-status: "up"
    - id: "b06f8043-f96b-4279-8f0a-0e128a73cc32"
      name: "CFS"
      shortName: "cfs"
      description: "The Community File System (CFS) is a global file system available on all NERSC computational systems."
      lastModified: "2025-03-03T07:51:20.672-00:00"
      links:
        - rel: "self"
          href: "/api/v1/status/resources/b06f8043-f96b-4279-8f0a-0e128a73cc32"
      type: "storage"
      group: "storage"
      current-status: "up"
    - id: "ff415c87-6596-41c7-93fd-b772994a92d4"
      name: "Global Homes"
      shortName: "global_homes"
      description: "Home directories provide a convenient means for a user to have access to files such as dotfiles, source files, and configuration files."
      lastModified: "2025-03-03T07:51:20.672-00:00"
      links:
        - rel: "self"
          href: "/api/v1/status/resources/ff415c87-6596-41c7-93fd-b772994a92d4"
      type: "storage"
      group: "storage"
      current-status: "up"
    - id: "0918ad2e-b318-4fd1-ac8f-56a55abf8e8d"
      name: "Spin"
      shortName: "spin"
      description: "Spin is a container-based platform at NERSC designed for you to deploy your own science gateways, workflow managers, databases, API endpoints, and other network services to support your scientific projects."
      lastModified: "2025-03-03T07:51:20.672-00:00"
      links:
        - rel: "self"
          href: "/api/v1/status/resources/0918ad2e-b318-4fd1-ac8f-56a55abf8e8d"
      type: "service"
      group: "services"
      current-status: "up"
    - id: "f8a06086-b79b-4f45-beec-abb8bee38fa1"
      name: "CPU Nodes"
      shortName: "cpu"
      description: "CPU-based compute nodes."
      lastModified: "2025-03-03T07:51:20.672-00:00"
      links:
        - rel: "self"
          href: "/api/v1/status/resources/f8a06086-b79b-4f45-beec-abb8bee38fa1"
      type: "compute"
      group: "perlmutter"
      current-status: "up"
    - id: "057c3750-4ba1-4b51-accf-b160be683d80"
      name: "Data Transfer Nodes"
      shortName: "dtns"
      description: "The NERSC data transfer nodes provide access to Global Homes, Global Common, the Community File System (CFS), Perlmutter Scratch, and HPSS."
      lastModified: "2025-03-11T07:28:24.000-00:00"
      links:
        - rel: "self"
          href: "/api/v1/status/resources/057c3750-4ba1-4b51-accf-b160be683d80"
      type: "compute"
      group: "storage"
      current-status: "up"
    - id: "097c3750-4ba1-4b51-accf-b160be683d55"
      name: "Global Common"
      shortName: "global_common"
      description: "The Global Common File System is a global file system available on all NERSC computational systems."
      lastModified: "2025-03-03T07:51:20.672-00:00"
      links:
        - rel: "self"
          href: "/api/v1/status/resources/097c3750-4ba1-4b51-accf-b160be683d55"
      type: "storage"
      group: "storage"
      current-status: "up"
    - id: "13f886ac-6cc2-47c0-a5d4-d82daf3cf5c6"
      name: "Globus"
      shortName: "globus"
      description: "Globus is the recommended way to move significant amounts of data between NERSC and other sites."
      lastModified: "2025-03-03T07:51:20.672-00:00"
      links:
        - rel: "self"
          href: "/api/v1/status/resources/13f886ac-6cc2-47c0-a5d4-d82daf3cf5c6"
      type: "service"
      group: "services"
      current-status: "up"
    - id: "8b61b346-b53c-4a8e-83b4-776eaa14cc67"
      name: "GPU Nodes"
      shortName: "gpu"
      description: "GPU-based compute nodes."
      lastModified: "2025-03-03T07:51:20.672-00:00"
      links:
        - rel: "self"
          href: "/api/v1/status/resources/8b61b346-b53c-4a8e-83b4-776eaa14cc67"
      type: "compute"
      group: "perlmutter"
      current-status: "up"
    - id: "a0d96526-6fd3-413e-8f9e-ff12d602539e"
      name: "Superfacility API"
      shortName: "sfapi"
      description: "The Superfacility API aims to enable the use of all NERSC resources through purely automated means using popular development tools and techniques."
      lastModified: "2025-03-03T07:51:20.672-00:00"
      links:
        - rel: "self"
          href: "/api/v1/status/resources/a0d96526-6fd3-413e-8f9e-ff12d602539e"
      type: "service"
      group: "services"
      current-status: "up"
    - id: "43b698c6-ed4a-4c1c-90b6-f8829daa9e96"
      name: "HPSS Regent (Backup)"
      shortName: "regent"
      description: "The Superfacility API aims to enable the use of all NERSC resources through purely automated means using popular development tools and techniques."
      lastModified: "2025-03-03T07:51:20.672-00:00"
      links:
        - rel: "self"
          href: "/api/v1/status/resources/43b698c6-ed4a-4c1c-90b6-f8829daa9e96"
      type: "storage"
      group: "storage"
      current-status: "up"
    - id: "be85a1f4-292e-44d7-804d-68a7ca3e0a1e"
      name: "HPSS Regent (Backup)"
      shortName: "regent"
      description: "As the backup counterpart to the primary HPSS Archive, HPSS Regent ensures data availability during maintenance or unexpected downtimes of the main system."
      lastModified: "2025-03-03T07:51:20.672-00:00"
      links:
        - rel: "self"
          href: "/api/v1/status/resources/be85a1f4-292e-44d7-804d-68a7ca3e0a1e"
      type: "storage"
      group: "storage"
      current-status: "up"
    - id: "b1ce8cd1-e8b8-4f77-b2ab-152084c70281"
      name: "Login Nodes"
      shortName: "login"
      description: "In the NERSC system, login nodes are where users can log in, edit files, and submit jobs."
      lastModified: "2025-03-03T07:51:20.672-00:00"
      links:
        - rel: "self"
          href: "/api/v1/status/resources/b1ce8cd1-e8b8-4f77-b2ab-152084c70281"
      type: "compute"
      group: "perlmutter"
      current-status: "up"
    - id: "72c11ef6-ff6b-409e-adfd-2f3763daac4f"
      name: "Gitlab"
      shortName: "gitlab"
      description: "Gitlab is git-based code hosting service at NERSC."
      lastModified: "2025-03-03T07:51:20.672-00:00"
      links:
        - rel: "self"
          href: "/api/v1/status/resources/72c11ef6-ff6b-409e-adfd-2f3763daac4f"
      type: "service"
      group: "services"
      current-status: "up"
    - id: "3594b493-f811-43b9-9c14-a3dd23542ffc"
      name: "Network"
      shortName: "network"
      description: "The networking infrastructure for services at NERSC."
      lastModified: "2025-03-03T07:51:20.672-00:00"
      links:
        - rel: "self"
          href: "/api/v1/status/resources/3594b493-f811-43b9-9c14-a3dd23542ffc"
      type: "service"
      group: "services"
      current-status: "up"
    - id: "d3c52e3c-dd2a-47a4-91e7-f06e00cf486d"
      name: "jupyter.nersc.gov"
      shortName: "jupyter"
      description: "Jupyter is a literate computing software ecosystem for working with digital documents called notebooks that can contain executable code, equations, visualizations, interactive interfaces, text, and metadata."
      lastModified: "2025-03-03T07:51:20.672-00:00"
      links:
        - rel: "self"
          href: "/api/v1/status/resources/d3c52e3c-dd2a-47a4-91e7-f06e00cf486d"
      type: "website"
      group: "websites"
      current-status: "up"
    - id: "b951a092-7f0a-4263-bc9a-700c7ceed415"
      name: "portal[auth].nersc.gov"
      shortName: "portal"
      description: "Science gateways."
      lastModified: "2025-03-03T07:51:20.672-00:00"
      links:
        - rel: "self"
          href: "/api/v1/status/resources/b951a092-7f0a-4263-bc9a-700c7ceed415"
      type: "website"
      group: "websites"
      current-status: "up"
  incidents:
  events:
  locations:
    - id: "b1c7773f-4624-4787-b1e9-46e1c78c3320"
      name: "Lawrence Berkeley National Laboratory"
      shortName: "LBNL"
      description: "Lawrence Berkeley National Laboratory is a U.S. DOE Office of Science national laboratory managed by the University of California."
      lastModified: "2025-03-04T09:00:00.690-00:00"
      links:
        - rel: "self"
          href: "/api/v1/status/locations/b1c7773f-4624-4787-b1e9-46e1c78c3320"
      countryName: "United States of America"
      localityName: "Berkeley"
      stateOrProvinceName: "California"
      streetAddress: "1 Cyclotron Rd."
      unlocode: "US JBK"
      altitude: 240
      latitude: 37.87492
      longitude: -122.2529
