#############################################################################
#  IRI Facility API reference implementation Copyright (c) 2025,
#  The Regents of the University of California, through Lawrence
#  Berkeley National Laboratory (subject to receipt of any required
#  approvals from the U.S. Dept. of Energy).  All rights reserved.
#
#  If you have questions about your rights to use or distribute this
#  software, please contact Berkeley Lab's Innovation & Partnerships
#  Office at IPO@lbl.gov.
#
#  NOTICE.  This Software was developed under funding from the
#  U.S. Department of Energy and the U.S. Government consequently retains
#  certain rights. As such, the U.S. Government has been granted for
#  itself and others acting on its behalf a paid-up, nonexclusive,
#  irrevocable, worldwide license in the Software to reproduce,
#  distribute copies to the public, prepare derivative works, and perform
#  publicly and display publicly, and to permit other to do so.
#############################################################################

# Standard spring runtime configuration.
server:
  port: 8081  # Change to the desired port number
  shutdown: graceful
  servlet:
    context-path: /
  compression:
    enabled: true
  server-header: "DOE IRI Demo Server"

# Standard logging runtime configuration.
logging:
  level:
    root: INFO
    net.es.iri.api.facility: DEBUG  # Change package-level logging

# This is the path to expose the swagger-generated documentation.
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /v3/swagger-ui

#########################################
# Spring Boot actuator configuration.   #
#########################################
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      status:
        http-mapping:
          down: 500
          out_of_service: 503
          warning: 500
    shutdown:
      enabled: false

  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health, info
    shutdown:
      enabled: false

  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

  info:
    java.enabled: true
    env.enabled: true
    git:
      enabled: true
      mode: full

#####################################################
# Application-specific configuration.               #
#####################################################
iri:
  server:
    root: "http://localhost:8081"
    #proxy: "https://iri.es.net"

  status:
    facility: src/test/resources/facility.json
    sites: src/test/resources/sites.json
    locations: src/test/resources/locations.json
    incidents: src/test/resources/incidents.json
    events: src/test/resources/events.json
    resources: src/test/resources/resources.json

  account:
    capabilities: src/test/resources/capabilities.json
    projects: src/test/resources/projects.json
    project_allocations: src/test/resources/project_allocations.json
    user_allocations: src/test/resources/user_allocations.json