#############################################################################
#  IRI Facility API reference implementation Copyright (c) 2025,
#  The Regents of the University of California, through Lawrence
#  Berkeley National Laboratory (subject to receipt of any required
#  approvals from the U.S. Dept. of Energy).  All rights reserved.
#
#  If you have questions about your rights to use or distribute this
#  software, please contact Berkeley Lab's Innovation & Partnerships
#  Office at IPO@lbl.gov.
#
#  NOTICE.  This Software was developed under funding from the
#  U.S. Department of Energy and the U.S. Government consequently retains
#  certain rights. As such, the U.S. Government has been granted for
#  itself and others acting on its behalf a paid-up, nonexclusive,
#  irrevocable, worldwide license in the Software to reproduce,
#  distribute copies to the public, prepare derivative works, and perform
#  publicly and display publicly, and to permit other to do so.
#############################################################################

# Standard spring runtime configuration.
server:
  port: 8443  # Change to the desired port number
  servlet:
    context-path: /
  ssl:
    enabled: true
    key-store: /iri/config/keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: myalias

# Standard logging runtime configuration.
logging:
  level:
    root: INFO
    net.es.iri.api.facility: DEBUG  # Change package-level logging

# This is the path to expose the Swagger-generated documentation.
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /v3/swagger-ui

# Application-specific configuration.
iri:
  server:
    root: "http://localhost:8443"
    #proxy: "https://iri.es.net"

  status:
    facility: /iri/config/facility.json
    sites: /iri/config/sites.json
    locations: /iri/config/locations.json
    incidents: /iri/config/incidents.json
    events: /iri/config/events.json
    resources: /iri/config/resources.json